export enum NotificationType {
  MISSION_SUCCESS = "MISSION_SUCCESS",
  MISSION_FAILED = "MISSION_FAILED",
  SUPPORTER_ASSIGNED = "SUPPORTER_ASSIGNED",
  SUPPORTER_DISMISSED = "SUPPORTER_DISMISSED",
}
